- name: Install and run Docker
  hosts: node01
  become: true
  gather_facts: yes
  vars:
    user_name: ansible

  tasks:
    - name: Update apt cache (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - pip
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add user to docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: Change ownership of Docker socket
      file:
        path: /var/run/docker.sock
        owner: "{{ user_name }}"
        group: docker
        mode: '0666'

    - name: Restart Docker daemon
      service:
        name: docker
        state: restarted

    - name: Install Docker SDK for Python library
      pip:
        name: docker
        state: present

    - name: Pull Jenkins Docker image
      docker_image:
        name: jenkins/jenkins
        source: pull
        state: present

    - name: Set permissions for Jenkins volume
      file:
        path: /var/jenkins_home
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"

    - name: Create Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "/var/jenkins_home:/var/jenkins_home"
        restart_policy: always
        container_default_behavior: compatibility

